version: '3.5'

services:
  frontend:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app:z
    ports:
      - ${CLIENT_PUBLIC_PORT}:${CLIENT_CONTAINER_PORT}
    env_file: .env
    command: npm run start
    links:
      - server:server
    depends_on:
      - server

  server:
    image: node:14-alpine
    volumes:
      - ./server:/app:z
    ports:
      - ${SERVER_PUBLIC_PORT}:${SERVER_CONTAINER_PORT}
    working_dir: /app
    command: npm run dev
    depends_on:
      - database
    env_file: .env

  database:
    image: mariadb:10.5
    volumes:
      - ./database/mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_PUBLIC_PORT}:${PHPMYADMIN_CONTAINER_PORT}
    restart: always
    depends_on:
      - database
    links:
      - database
    env_file: .env
# version: "3.5"

# services:
#   # client:
#   #   image: node:17-alpine
#   #   working_dir: /app
#   #   volumes:
#   #     - ./client:/app
#   #   ports:
#   #     - ${CLIENT_PUBLIC_PORT}:${CLIENT_CONTAINER_PORT}
#   #   # command: npm start
#   #   env_file:
#   #     - .env

#   server:
#     image: node:17-alpine
#     working_dir: /app
#     volumes:
#       - ./backend:/app
#     ports:
#       - ${SERVER_PUBLIC_PORT}:${SERVER_CONTAINER_PORT}
#     command: npm start
#     depends_on:
#       - database
#     env_file:
#       - .env

#   database:
#     image: mariadb:10.5.13
#     volumes:
#       # - ./nextjs.sql:/docker-entrypoint-initdb.d/nextjs.sql
#       - ./database/data:/var/lib/mysql
#     environment:
#       - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
#     env_file: .env

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     ports:
#       - ${PHPMYADMIN_PUBLIC_PORT}:${PHPMYADMIN_CONTAINER_PORT}
#     environment:
#       - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
#       - PMA_HOST=database
#     env_file:
#       - .env
#     depends_on:
#       - database
